### PR TITLE
Preserving Entity Fuzziness

### PR DESCRIPTION
**Pull request by knowtheory**
Hey PRX folks!  Hello from DocumentCloud!

We were doing some final testing in our switch away from Calais old API and noticed that your Calais gem knocks out any match that doesn't literally match the entity name.

So, here's a pull request that preserves the existing behavior but provides an option to get all of the entity data.

### CODE REVIEW

**Comment by kookster** [comment]
cool, nice change  - very helpful.
Any tests to go with it?

**Comment by knowtheory** [comment]
tktk :)

(I've been integration/acceptance testing by hand, test automation to follow)

**Comment by knowtheory** [comment]
a better name for the option other than `:exact` is probably a good idea too.  I'm curious what the intent was in only doing literal matches (maybe that can provide a hint to what the option should be called)

**Comment by kookster** [comment]
I think what it is doing is knocking out any instance that *is* an exact match - it is selecting where they do *not* (!=) match exactly:
https://github.com/PRX/open_calais/blob/master/lib/open_calais/response.rb#L50

The reason was because I was only interested in the entity names, as a kind of tag, not the additional info of where in the text it had appeared.  We index the text anyway, so those matches / search results are redundant.

It is possibly interesting, for my purposes, when there is a match where the name of the entity does not itself appear in the text, but has been fuzzily matched in some way by open calais, so only those instances were returned.

**Comment by knowtheory** [comment]
Ah, yep you're totally right, apologies, in my haste, i mostly just noticed that there was data missing that we expected.  So the option more correctly should be something like `:ignore_literal_match` and default to `true`

**Comment by kookster** [comment]
I made a new PR so I could finish updating the option name, but it's merged now.

**Pull request merged**
